// Generated by CoffeeScript 1.7.1
Package.describe({
  summary: "A pattern to display application errors to the user."
});

Package.on_use(function(api, where) {
  api.use(['minimongo', 'mongo-livedata', 'templating'], 'client');
  
  api.add_files(['errors.js', 'errors_list.html', 'errors_list.js'], 'client');
  
  if (api.export) {
    return api.export('Errors');
  }
});
